# Generated by Django 3.1.5 on 2021-01-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='encrypted_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendby', models.CharField(default='none', max_length=30)),
                ('sendto', models.CharField(default='none', max_length=30)),
                ('nrmlimg', models.ImageField(upload_to='pics')),
                ('msg', models.TextField()),
                ('sensitivity', models.TextField()),
                ('secret_key', models.TextField()),
                ('encryimg', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
